# Generated by Django 5.1.6 on 2025-02-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='owner',
            new_name='user',
        ),
    ]
