# Generated by Django 5.1.6 on 2025-02-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_basketitem_processing_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='processing_object',
        ),
    ]
