# Generated by Django 5.1.5 on 2025-03-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_stripe_payment_intent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment_intent',
            new_name='stripe_payment_intent_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('ONLINE', 'ONLINE'), ('STRIPE', 'STRIPE')], default='COD', max_length=15),
        ),
    ]
