# Generated by Django 5.1.5 on 2025-03-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0013_alter_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Seller', 'Seller'), ('Farmer', 'Farmer'), ('Foreign_buyer', 'Foreign_buyer')], default='Admin', max_length=50),
        ),
    ]
